name    'anl-hierapkgs'
version '0.1.0'
source 'https://github.com/anl/puppet-hierapkgs.git'
author 'anl'
license 'Apache License, Version 2.0'
summary 'hierapkgs module'
description 'Install a merged array of packages from Hiera'
project_page 'https://github.com/anl/puppet-hierapkgs'

dependency 'puppetlabs/stdlib', '>=3.2.0'
